### ISSUE TITLE
AttributeError: 'DGLBlock' object has no attribute 'create_format_'

### ISSUE THREAD

**Issue by GlennCGL** [damo-cv/Ada-NETS#1]
When running 'sh script/train_GCN.sh', meet questions below. My dgl version is 0.6.1. Have you met this before?

  File "train.py", line 58, in collate
    block1.create_format_()
AttributeError: 'DGLBlock' object has no attribute 'create_format_'

**Comment by Thomas-wyh** [comment]
Please look at this [requirements.txt](https://github.com/damo-cv/Ada-NETS/requirements.txt).
You'd better use dgl-cu102==0.5.0 because the API of DGL often changes.
