### ISSUE TITLE
failure.... need help

### ISSUE THREAD

**Issue by ThomaswellY** [damo-cv/Ada-NETS#10]
when executed "pip install -r requirements.txt", Error was shown as below:
ERROR: Could not find a version that satisfies the requirement faiss==1.6.3 (from versions: none)
ERROR: No matching distribution found for faiss==1.6.3
So i noted "#faiss==1.6.3"and"#apex==0.1"(cause for the same issue)，the residual requirements parts were installed successfully.
what to deal with the version issue? are there any alternatives version of faiss and apex?
thanks sincerely!

**Comment by ThomaswellY** [comment]
I set apex==0.9.10.dev0  and faiss==1.5.3 becaurse there are no other versions available,  apex for https://github.com/NVIDIA/apex was cloned successfully, when i execute the command "pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./", Error was shown below:
/home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/pip/_internal/commands/install.py:229: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 21.2.2 from /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/pip (python 3.6)
Processing /home/yanghao/project/Ada-NETS/apex
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    Running command python setup.py egg_info
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

    Warning: Torch did not find available GPUs on this system.
     If your intention is to cross-compile, this is not an error.
    By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
    Volta (compute capability 7.0), Turing (compute capability 7.5),
    and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
    If you wish to cross-compile for a single specific architecture,
    export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.



    torch.__version__  = 1.2.0


    running egg_info
    creating /tmp/pip-pip-egg-info-l4kc3h8o/apex.egg-info
    writing /tmp/pip-pip-egg-info-l4kc3h8o/apex.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-l4kc3h8o/apex.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-l4kc3h8o/apex.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-l4kc3h8o/apex.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-l4kc3h8o/apex.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file '/tmp/pip-pip-egg-info-l4kc3h8o/apex.egg-info/SOURCES.txt'
Skipping wheel build for apex, due to binaries being disabled for it.
Installing collected packages: apex
  Attempting uninstall: apex
    Found existing installation: apex 0.9.10.dev0
    Uninstalling apex-0.9.10.dev0:
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex-0.9.10.dev0.dist-info/
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/__init__.py
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/__pycache__/
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/decorators.py
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/exceptions.py
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/ext/
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/forms.py
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/i18n.py
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/interfaces.py
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/lib/
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/locale/
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/models.py
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/scaffolds/
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/static/css/
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/static/images/
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/templates/
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/tests/__init__.py
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/tests/__pycache__/
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/tests/test_lib_libapex.py
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/tests/test_views.py
      Removing file or directory /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/views.py
      Successfully uninstalled apex-0.9.10.dev0
    Running command /home/yanghao/anaconda3/envs/adanets/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8b7u_kzu/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8b7u_kzu/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-oyj91f5e/install-record.txt --single-version-externally-managed --compile --install-headers /home/yanghao/anaconda3/envs/adanets/include/python3.6m/apex
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

    Warning: Torch did not find available GPUs on this system.
     If your intention is to cross-compile, this is not an error.
    By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
    Volta (compute capability 7.0), Turing (compute capability 7.5),
    and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
    If you wish to cross-compile for a single specific architecture,
    export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.



    torch.__version__  = 1.2.0


    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-8b7u_kzu/setup.py", line 175, in <module>
        check_cuda_torch_binary_vs_bare_metal(CUDA_HOME)
      File "/tmp/pip-req-build-8b7u_kzu/setup.py", line 27, in check_cuda_torch_binary_vs_bare_metal
        torch_binary_major = torch.version.cuda.split(".")[0]
    AttributeError: 'NoneType' object has no attribute 'split'
    Running setup.py install for apex ... error
  Rolling back uninstall of apex
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex-0.9.10.dev0.dist-info/
   from /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/~pex-0.9.10.dev0.dist-info
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/__init__.py
   from /tmp/pip-uninstall-tdwvqrmn/__init__.py
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/__pycache__/
   from /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/~_pycache__
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/decorators.py
   from /tmp/pip-uninstall-tdwvqrmn/decorators.py
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/exceptions.py
   from /tmp/pip-uninstall-tdwvqrmn/exceptions.py
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/ext/
   from /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/~xt
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/forms.py
   from /tmp/pip-uninstall-tdwvqrmn/forms.py
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/i18n.py
   from /tmp/pip-uninstall-tdwvqrmn/i18n.py
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/interfaces.py
   from /tmp/pip-uninstall-tdwvqrmn/interfaces.py
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/lib/
   from /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/~ib
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/locale/
   from /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/~ocale
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/models.py
   from /tmp/pip-uninstall-tdwvqrmn/models.py
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/scaffolds/
   from /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/~caffolds
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/static/css/
   from /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/static/~ss
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/static/images/
   from /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/static/~mages
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/templates/
   from /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/~emplates
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/tests/__init__.py
   from /tmp/pip-uninstall-tdwvqrmn/tests/__init__.py
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/tests/__pycache__/
   from /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/tests/~_pycache__
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/tests/test_lib_libapex.py
   from /tmp/pip-uninstall-tdwvqrmn/tests/test_lib_libapex.py
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/tests/test_views.py
   from /tmp/pip-uninstall-tdwvqrmn/tests/test_views.py
  Moving to /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/apex/views.py
   from /tmp/pip-uninstall-tdwvqrmn/views.py
ERROR: Command errored out with exit status 1: /home/yanghao/anaconda3/envs/adanets/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8b7u_kzu/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8b7u_kzu/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-oyj91f5e/install-record.txt --single-version-externally-managed --compile --install-headers /home/yanghao/anaconda3/envs/adanets/include/python3.6m/apex Check the logs for full command output.
(adanets) /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/pip/_internal/commands/install.py:229: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 21.2.2 from /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/pip (python 3.6)
Processing /home/yanghao/project/Ada-NETS/apex
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find-sh: 32: /home/yanghao/anaconda3/envs/adanets/lib/python3.6/site-packages/pip/_internal/commands/install.py:229:: not found
(adanets) -sh: 33: Syntax error: word unexpected (expecting ")")
(adanets) -sh: 33: Syntax error: "(" unexpected
(adanets) -sh: 33: Processing: not found
(adanets) -sh: 34: DEPRECATION:: not found
I would be so appreciate of you ,if you can give me anyhelp!

**Comment by Thomas-wyh** [comment]
Hi !
1. You can try install faiss by conda，or change the pip source, or install with the latest version.

2.  Ada-NETS can also run without apex.  You just comment the import apex in GCN/train.py and set fp16:False in GCN/config.yml.

Please let me know if you have any problems.
