### ISSUE TITLE
关于论文中没有给出η的值

### ISSUE THREAD

**Issue by Y1YU** [damo-cv/Ada-NETS#12]
在论文中的等式2中，定义了新的相似度等于jaccard相似度和cosine相似度的加权和，使用到参数η。但是我在论文中并没有找到实验时这个参数的定义，在代码中发现一个参数lamb=0.3，但是加权的是距离。

所以代码中的lamb=0.3相当于论文中的η=0.7？

**Comment by Thomas-wyh** [comment]
Yes.
Thank you for your careful reading.
Some details need to be found in the code due to the limited space of the paper.
