### ISSUE TITLE
failed to get the same performance

### ISSUE THREAD

**Issue by zzzzzero** [damo-cv/Ada-NETS#13]
Thank you for your great work.
I run the train and test scripts on the ms1m dataset these days,but I got poor performance.
Here are my result on ms1m part1_test:
Bcubed fscore:0.6264, parwise fscore 0.4994.
I wonder which step went wrong，could you share the training log?
When I run the train_GCN script ,the last loss is:
loss:1.9265 bclloss_pos:0.007  bclloss_neg:1.919

**Comment by Thomas-wyh** [comment]
Don't Worry.
Can you tell me `trainmre` and  `testmre` result of adaptive filter after training?

**Comment by zzzzzero** [comment]
trainkdiff 5.21 testkdiff 8.04
trainmre:0.11  testmre:0.32

**Comment by zzzzzero** [comment]
After I change  the version of dgl ,the performance is normal.
