### ISSUE TITLE
关于MSMT17数据集的问题

### ISSUE THREAD

**Issue by floydzero** [damo-cv/Ada-NETS#2]
恭喜您的团队论文高中，请问有公开MSMT17数据集提取后特征的计划吗？我们组也在研究相关工作，十分想follow一下您的工作。祝您生活愉快，工作顺利。

**Comment by slacklife** [comment]
MSMT17 feature and label files have been released. See [here](https://github.com/damo-cv/Ada-NETS#data-preparation)  to access the data.

Best wishes!

**Comment by Thomas-wyh** [comment]
MSMT17 feature and label files have been released. See [here](https://github.com/damo-cv/Ada-NETS#data-preparation) to access the data.

Best wishes!

**Comment by floydzero** [comment]
非常感谢您的慷慨帮助！祝您及团队成员身体健康，诸事顺心，科研工作顺利！
Thank you very much for your generous help！
