### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by fuyuyuputao** [damo-cv/Ada-NETS#3]
前辈您好：
       
        首先恭喜您的团队论文高中
      
![}LUG5SI37(_ZHZOKM_5O)BB](https://user-images.githubusercontent.com/79823933/168552187-71fb926f-e027-49e7-a7b8-24dd76f61893.png)

       关于您提供的数据集，在上图数字“2”标注处，下载下来的数据，训练集数据是30248，测试集数据是93820，而上图数字“1”标注处，进入“1”的链接后下载的数据（Part1 (584K): GoogleDrive or BaiduYun (passwd: geq5)），训练集数据是576494，测试集数据是584013。
       在上图数字“2”标注处下载的数据上，也就是训练集数据是30248，测试集数据是93820，最终效果达不到您论文所述，和您论文结果相差很大。想请教您一下，您在训练模型和测试模型的时候，训练集和测试集数量分别设置的是多少？

**Comment by Thomas-wyh** [comment]
Hi, Thank you for your interest in Ada-NETS.
The training and test sets were partitioned strictly following previous work as described in the paper.
I suggest you experiment on MS-Celeb first, as the publicly available code parameters of this repository are perfectly matched in this dataset.
If there are other issues, please post some intermediate results or logs for further analysis.

Best wishes!

**Comment by niujindacidian** [comment]
@Thomas-wyh 前辈您好， 图中框起来的部分 ‘here ’ 这里链接失效了，无法下载MSMT17的相关数据，麻烦您帮忙看看。
![56461e012efa4f4a8730de6acbcc86ec](https://github.com/damo-cv/Ada-NETS/assets/44803437/a200f1c7-dd44-49e1-9d1c-38829f3c3ffb)

**Comment by fuyuyuputao** [comment]
> @Thomas-wyh前您生成好，句子框起来的部分“这里”这里链接失效了，无法下载MSMT17的相关数据，麻烦您帮忙看看。 ![56461e012efa4f4a8730de6acbcc86ec](https://private-user-images.githubusercontent.com/44803437/297304944-a200f1c7-dd44-49e1-9d1c-38829f3c3ffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzkyMDksIm5iZiI6MTcwNTQ3ODkwOSwicGF0aCI6Ii80NDgwMzQzNy8yOTczMDQ5NDQtYTIwMGYxYzctZGQ0NC00OWUxLTlkMWMtMzg4MjlmM2MzZmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA4MDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOGIwZWYwM2M4MDM0OTJlNzM4NWM1NmZlNWM0ZTg3ZGM4OWUzZGE5NWZjYzU5YzRiNTAwN2YzMTA3ZGYwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WqGAfuMOqZrd54GKHwP3dazm8axCmEFg5s3RbQEcERg)

这个我忘了，不过你可以试试用wget命令下载？加油！

**Comment by niujindacidian** [comment]
> > @Thomas-wyh前您生成好，句子框起来的部分“这里”这里链接失效了，无法下载MSMT17的相关数据，麻烦您帮忙看看。 ![56461e012efa4f4a8730de6acbcc86ec](https://private-user-images.githubusercontent.com/44803437/297304944-a200f1c7-dd44-49e1-9d1c-38829f3c3ffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NzkyMDksIm5iZiI6MTcwNTQ3ODkwOSwicGF0aCI6Ii80NDgwMzQzNy8yOTczMDQ5NDQtYTIwMGYxYzctZGQ0NC00OWUxLTlkMWMtMzg4MjlmM2MzZmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDA4MDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOGIwZWYwM2M4MDM0OTJlNzM4NWM1NmZlNWM0ZTg3ZGM4OWUzZGE5NWZjYzU5YzRiNTAwN2YzMTA3ZGYwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WqGAfuMOqZrd54GKHwP3dazm8axCmEFg5s3RbQEcERg)
> 
> 这个我忘了，不过你可以试试用wget命令下载？加油！

好的，谢谢啦，我试试。
