### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data/adj/test/adj_adanets.npz'

### ISSUE THREAD

**Issue by changgongcheng** [damo-cv/Ada-NETS#5]

**Comment by changgongcheng** [comment]
当执行script/train_GCN.sh时，报错，求助

**Comment by Thomas-wyh** [comment]
Try creating these paths first.
e.g. 
mkdir -p  data/adj/test/

If there are still problems, please post some intermediate results or logs for further analysis.

**Comment by changgongcheng** [comment]
> Try creating these paths first. e.g. mkdir -p data/adj/test/
> 
> If there are still problems, please post some intermediate results or logs for further analysis.

这些路径都已经生成了。

**Comment by changgongcheng** [comment]
> Try creating these paths first. e.g. mkdir -p data/adj/test/
> 
> If there are still problems, please post some intermediate results or logs for further analysis.

还是一样。

**Comment by Thomas-wyh** [comment]
Can you give me any intermediate results or logs for analysis?
