### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'outpath/ckpt_40000.pth'

### ISSUE THREAD

**Issue by Nigar21** [damo-cv/Ada-NETS#8]
Dear author, 

when I run>>bash script/train_AND.sh

I get: FileNotFoundError: [Errno 2] No such file or directory: 'outpath/ckpt_40000.pth'

all the other necessary folders are created, but the 'AND/outpath' folder is actually empty. I downloaded the pretrained checkpoints but the mentioned one in the error is not there. 
Maybe I miss downloading smtn else?

**Comment by Thomas-wyh** [comment]
Please uncomment the Line21 in script/train_AND.sh [here](https://github.com/damo-cv/Ada-NETS/blob/main/script/train_AND.sh#L21)  and run it again.

**Comment by Nigar21** [comment]
Thank you soo much!
