### ISSUE TITLE
NameError: name 'knn' is not defined

### ISSUE THREAD

**Issue by Nigar21** [damo-cv/Ada-NETS#9]
also, when I run >>bash script/gene_adj.sh I got this:
Traceback (most recent call last):
File "tool/gene_adj_adanets.py", line 3, in
from knn import fast_knns2spmat, knns2ordered_nbrs, fast_knns2spmat_adaptivek
File "/home/nigar/Ada-NETS/tool/knn.py", line 289, in
class knn_brute_force(knn):
NameError: name 'knn' is not defined

**Comment by Thomas-wyh** [comment]
Hi, thanks for your issue. 
Please comment the Line289~398 in tool/knn.py. These codes are not used in this project.
Also, uncomment the Line10 in script/gene_adj.sh.

These will be fixed later.
